apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Sharks-EKS-cluster
  region: us-east-2

nodeGroups:
  - name: Sharks-ng
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName: eks