apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat-deployment
  replicas: 2

  template:
    metadata:
      labels:
        app: tomcat-deployment
    spec:
      containers:
      - name: tomcat-deployment-container
        image: sharksdocker/simple-devops-image
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080